services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: cie_manager_backend
    env_file:
      - .env
    ports:
      - "12000:8000"
    restart: unless-stopped
    volumes:
      - media_data:/app/mediafiles
      - static_data:/app/staticfiles

volumes:
  media_data:
  static_data:
