services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: cie_manager_backend
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped
    volumes:
      - media_data:/app/mediafiles
      - static_data:/app/staticfiles
    networks:
      - app-network
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: cie_manager_nginx
    ports:
      - "12000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/app/staticfiles:ro
      - media_data:/app/mediafiles:ro
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  media_data:
  static_data:

networks:
  app-network:
    driver: bridge
