"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from datetime import timedelta
from pathlib import Path
from decouple import config, Csv
from django.core.files.storage import storages
from storages.backends.s3boto3 import S3Boto3Storage


# === PATHS ===
BASE_DIR = Path(__file__).resolve().parent.parent


STATIC_URL = "/static/"
# STATICFILES_DIRS = [BASE_DIR / "static"]  # optional
STATIC_ROOT = BASE_DIR / "staticfiles"  

# === SECURITY ===
SECRET_KEY = config('SECRET_KEY', default='unsafe-default-key')
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

# === Cloudflare R2 Configuration ===
USE_S3 = config('USE_S3', default=False, cast=bool)
if USE_S3:
	AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
	AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
	AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
	AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')
	AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='auto')
	AWS_S3_ADDRESSING_STYLE = config('AWS_S3_ADDRESSING_STYLE', default='path')
	AWS_QUERYSTRING_AUTH = True
	DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
	storages._storages.clear()
	storages._storages["default"] = S3Boto3Storage()

# === APPLICATIONS ===
INSTALLED_APPS = [
	'corsheaders',
	'accounts',
	'management',

	'storages',
	'rest_framework',
	'rest_framework_simplejwt',
	'debug_toolbar',
	'django_extensions',

	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
]

# === MIDDLEWARE ===
MIDDLEWARE = [
	'corsheaders.middleware.CorsMiddleware',
	'debug_toolbar.middleware.DebugToolbarMiddleware',
	"management.middleware.CurrentUserMiddleware",


	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# === URLS & WSGI ===
ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'

# === TEMPLATES ===
TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

# === DATABASE ===
DATABASES = {
	'default': {
		'ENGINE': config('DB_ENGINE', default='django.db.backends.sqlite3'),
		'NAME': config('DB_NAME', default=BASE_DIR / 'db.sqlite3'),
		'USER': config('DB_USER', default=''),
		'PASSWORD': config('DB_PASSWORD', default=''),
		'HOST': config('DB_HOST', default=''),
		'PORT': config('DB_PORT', default=''),
	}
}

# === PASSWORD VALIDATION ===
AUTH_PASSWORD_VALIDATORS = [
	{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
	{'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
	{'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
	{'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === INTERNATIONALIZATION ===
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# === AUTHENTICATION ===
AUTH_COOKIE = 'access_token'
AUTH_USER_MODEL = 'accounts.User'

# === STATIC FILES ===
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'mediafiles'

# === DEFAULT PRIMARY KEY FIELD TYPE ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === REST FRAMEWORK ===
REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'accounts.authentication.CookieJWTAuthentication',
		'rest_framework_simplejwt.authentication.JWTAuthentication',
	),
	'DEFAULT_PERMISSION_CLASSES': (
		'rest_framework.permissions.IsAuthenticated',
	),
}

# === JWT Configuration ===
SIMPLE_JWT = {
	'ACCESS_TOKEN_LIFETIME': timedelta(days=5),
	'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
	'ROTATE_REFRESH_TOKENS': True,
	'BLACKLIST_AFTER_ROTATION': True,
	'ALGORITHM': 'HS256',
	'SIGNING_KEY': SECRET_KEY,
	'VERIFYING_KEY': None,
	'AUDIENCE': None,
	'ISSUER': None,
	'USER_ID_FIELD': 'id',
	'USER_ID_CLAIM': 'user_id',
	'AUTH_HEADER_TYPES': ('Bearer',),
	'TOKEN_TYPE_CLAIM': 'token_type',
	'TOKEN_USER_CLAIM': 'user',
}

# === Internal Ips ===
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
	"192.168.1.171"
]

# === Graph Models ===
# GRAPH_MODELS = {
#   'all_applications': True,
#   'group_models': True,
# }

# === CORS / CSRF ===
CORS_ALLOW_CREDENTIALS = True

# Allow origins from env (comma-separated), plus local dev by default
_frontend_origins = config('FRONTEND_ORIGINS', default='', cast=Csv())
CORS_ALLOWED_ORIGINS = [
	"http://localhost:12000",
	"http://192.168.1.171:12001",
] + _frontend_origins

# Optional regex support for dynamic preview domains (e.g., Vercel)
_cors_regexes = config('CORS_ALLOWED_ORIGIN_REGEXES', default='', cast=Csv())
if _cors_regexes:
	CORS_ALLOWED_ORIGIN_REGEXES = _cors_regexes

CSRF_TRUSTED_ORIGINS = [
	"http://localhost:12001",
	"http://192.168.1.171:12001",
] + [o.replace('http://', 'http://').replace('https://', 'https://') for o in _frontend_origins]

# Cross-site cookies for frontend on different domain
if DEBUG:
	SESSION_COOKIE_SAMESITE = "Lax"
	CSRF_COOKIE_SAMESITE = "Lax"
else:
	SESSION_COOKIE_SAMESITE = "None"
	CSRF_COOKIE_SAMESITE = "None"

SESSION_COOKIE_SECURE = False if DEBUG else True
CSRF_COOKIE_SECURE = False if DEBUG else True